file = open("notes.txt", 'w')
file.write("This is written using 'w' mode.\n")
file.close()
file = open("notes.txt", 'r')
print(file.read())
file.close()
file = open("notes.txt", 'a')
file.write("This line is added using 'a' mode.\n")
file.close()

file = open("notes.txt", 'r+')
print(file.read())  
file.write("Added this line using 'r+' mode.\n")  
file.close()

file = open("notes.txt", 'w+')
file.write("This content is written using 'w+' mode.\n")
file.seek(0) 
print(file.read())
file.close()

file = open("notes.txt", 'a+')
file.write("This is appended using 'a+' mode.\n")
file.seek(0)  
print(file.read())
file.close()
